#!/usr/bin/env bash
#
#
# Testing sysinfo
# By: Marcelo Alves
# No Copyright, license or any shit. Intelectual property doesn't exists.

# System information

os="$(sed -rn '/^NAME/ s/^NAME="?([a-z A-Z]+).?$/\1/p' /etc/os-release)"
kernel="$(uname -sr)"
hostname="$(uname -n)"
host="$(cat /sys/devices/virtual/dmi/id/product_name)"
bios="$(echo $(cat /sys/devices/virtual/dmi/id/bios_{vendor,version}))"
cpu="$(awk -F ': ' '/model name/ {printf $2; exit}' /proc/cpuinfo)"
cpu_bugs="$(awk -F ': ' '/bugs/ {print $2; exit}' /proc/cpuinfo)"
mem_info="$(free -m | awk '/Mem/{print $3"MiB", $2"MiB"}' OFS=' / ')"
shell="$(basename $SHELL)"

# Clear screen
clear 

# Print sysinfo
cat <<EOF 

Well, some information about your system.
Let's go.

OS:		${os}
Hostname:	${hostname}
Host:		${host}
Bios:		${bios}
Kernel:		${kernel}
Processor:	${cpu}
CPU Bugs:	${cpu_bugs}
Memory:		${mem_info}
Shell:		${shell}

EOF







# Testing area
#
# userandhost="$(echo $(whoami)@$(uname -n))"
# mem_total="$(cat /proc/meminfo | awk '/MemTotal/ {printf $2}')"
# mem_usage="$(cat /proc/meminfo | awk '/Active/ {print $2}' | head -n 1)"
# mem_info="$(($mem_usage / 1024))MiB / $(($mem_total / 1024))MiB"
