#!/usr/bin/env bash
#
#
# Testing sysinfo
# By: Marcelo Alves
# No Copyright, license or any shit. Intelectual property doesn't exists.

# System information

os="$(sed -rn '/^NAME/ s/^NAME="?([a-z A-Z]+).?$/\1/p' /etc/os-release)"
kernel="$(uname -sr)"
hostname="$(uname -n)"
host="$(cat /sys/devices/virtual/dmi/id/product_name)"
bios="$(echo $(cat /sys/devices/virtual/dmi/id/bios_{vendor,version}))"
cpu="$(awk -F ': ' '/model name/ {printf $2; exit}' /proc/cpuinfo)"
cpu_cores="$(awk -F ': ' '/cpu cores/ {print $2; exit}' /proc/cpuinfo)"
cpu_threads="$(awk -F ': ' '/processor/ {print $2}' /proc/cpuinfo | wc -l)"
cpu_bugs="$(awk -F ': ' '/bugs/ {print $2; exit}' /proc/cpuinfo)"
mem_info="$(free -m | awk '/Mem/{print $3"MiB", $2"MiB"}' OFS=' / ')"
shell="$(basename $SHELL)"

# Colors
bold="$(tput bold)"
reset="$(tput sgr0)"
magenta="$(tput setaf 5)"

# Clear screen
clear 

# Print sysinfo
cat <<EOF 

${bold}${magenta}Well, some information about your system.
${bold}${magenta}Let's go.

${reset}

${bold}${magenta}OS:			${reset}${os}
${bold}${magenta}Hostname:		${reset}${hostname}
${bold}${magenta}Host:			${reset}${host}
${bold}${magenta}BIOS:			${reset}${bios}
${bold}${magenta}Kernel:			${reset}${kernel}
${bold}${magenta}Processor:		${reset}${cpu} - ${cpu_cores}C/${cpu_threads}T
${bold}${magenta}CPU Bugs:		${reset}${cpu_bugs}
${bold}${magenta}Memory:			${reset}${mem_info}
${bold}${magenta}Shell:			${reset}${shell}
${bold}${magenta}Terminal:		${reset}$TERM

EOF
